version: '3.5'

services:
    zookeeper:
      ports:
        - "2181:2181"
    broker0:
      ports:
        - "9092:9092"
    broker1:
      ports:
        - "9093:9092"
    broker2:
      ports:
        - "9094:9092"

    clickhouse-node1:
      ports:
        - "8123:8123"
        - "9000:9000"