version: '3.5'

services:
    zookeeper:
      ports:
        - "2181:2181"
    broker0:
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker2:29092
    broker1:
      ports:
        - "9093:9092"
      environment:
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9093,PLAINTEXT_INTERNAL://broker2:29092
    broker2:
      ports:
        - "9094:9092"
      environment:
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9094,PLAINTEXT_INTERNAL://broker2:29092

    clickhouse-node1:
      ports:
        - "8123:8123"
        - "9000:9000"